name: Continuous Integration (CI)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Run Unit Tests
        run: go test -v ./pkg/...

      - name: Build CLI Binary
        run: go build -o lontara ./cmd/lontara

      - name: Build WASM Binary
        run: GOOS=js GOARCH=wasm go build -o lontara.wasm ./cmd/wasm
